version: '3'

volumes:
  production_traefik: {}

services:
  streamlit:
    command: streamlit run app.py
    image: ${STREAMLIT_DOCKER_IMAGE:?err}
    container_name: streamlit_app
    restart: always
    expose:
      - "8501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 1m30s
      timeout: 10s
      retries: 3

    volumes:
      - type: bind
        source: $HOME/.OpenEye/
        target: /home/mambauser/.OpenEye/
      - type: bind
        source: .streamlit/secrets.toml
        target: /home/mambauser/.streamlit/secrets.toml
    env_file:
      - .env
  
  traefik:
    build:
      context: .
      dockerfile: ./Dockerfile.traefik
    image: traefik_production
    volumes:
      - production_traefik:/etc/traefik/acme:z
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"