version: '3'

services:
  falcbot:
    command: streamlit run app.py
    build: .
    container_name: "asap-ml-streamlit"
    ports:
      - 80:80
    volumes:
      - type: bind
        source: $HOME/.OpenEye/
        target: /home/mambauser/.OpenEye/