channels:
  - conda-forge
  - openeye


dependencies:
  # Base depends
  - python <3.11
  - pip

  - rdkit
  - pydantic<2.0a0
  - biopython
  - schedule
  - openeye-toolkits
  - asapdiscovery

  # ml
  - pytorch
  - pytorch_geometric >=2.5.0
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - numpy
  - h5py
  - e3nn
  - dgl
  - dgllife
  - pooch
  - mtenn >=0.5.1
  - wandb
  - semver

  # other asapdiscovery deps
  - distributed
  - dask
  - netifaces
  - boto3
  - pandas


    # Pip-only installs
  - pip:
    - streamlit-ketcher


