name: CI

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  # The cookiecutter uses the "--initial-branch" flag when it runs git-init
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/provision-with-micromamba
    # More info on options: https://github.com/mamba-org/provision-with-micromamba
      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          # default - will pull down 2.0 which we don't want!
          # micromamba-version: latest
          # pin to latest 1.x release
          micromamba-version: '1.5.10-0'
          environment-file: environment.yml
          environment-name: asap-ml-streamlit
          cache-environment: true
          cache-downloads: true
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}
          create-args: >-
            python==${{ matrix.python-version }}


      - name: Setup Conda Environment
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py
          pytest-args: -v --junit-xml=test-results.xml
      
      - if: always()
        uses: pmeier/pytest-results-action@v0.6.0
        with:
          path: test-results.xml
          summary: true
          display-options: fEX

